### ISSUE TITLE
provide a command line option to specify input file

### ISSUE THREAD

**Issue by harendra-kumar** [sol/hpack#106]
I am using stack and because of #104 I cannot keep a `package.yaml`. I want to be able to generate the cabal file from an arbitrary file say `hpack.yaml`. Otherwise I have to keep renaming to and from package.yaml to avoid #104. For such cases it will be useful to have a command line option to specify an input file such that:

```
hpack -f hpack.yaml
```

or read from stdin

```
hpack < hpack.yaml
```

**Comment by sol** [comment]
`hpack` already accepts a directory on the command line.  I'm ok to extend to include the file name provided that:

 - the cabal file is generated in the same directory as the input file
 - `hpack` emits a warning if the input file is not `package.yaml` (something along the lines the input file is foo instead of bar which may cause issues with third-party tools)

PRs accepted.
