### ISSUE TITLE
Support toml file format

### ISSUE THREAD

**Issue by mitchellwrosen** [sol/hpack#132]
https://github.com/toml-lang/toml

Any interest in adding support for accepting either `package.yaml` or `package.toml`?

It's a little more verbose than yaml (strings require quotes) but some people may prefer it. Example `package.toml`:

```toml
name       = "hpack"
version    = "0.15.0"
synopsis   = "An alternative format for Haskell packages"
maintainer = "Simon Hengel <sol@typeful.net>"
license    = "MIT"
github     = "sol/hpack"
category   = "Development"

ghc-options = "-Wall"

dependencies = [
  "base >= 4.7 && < 5",
  "base-compat >= 0.8",
  "deepseq",
  "directory",
  "filepath",
  "Glob",
  "htoml",
  "text",
  "containers",
  "unordered-containers",
  "yaml",
  "aeson >= 0.11",
]

[library]
source-dirs = "src"
exposed-modules = [
  "Hpack",
  "Hpack.Config",
  "Hpack.Run",
  "Hpack.Yaml",
]

[executables.hpack]
main = "Main.hs"
source-dirs = "driver"
dependencies = ["hpack"]

[tests.spec]
cpp-options = "-DTEST"
main        = "Spec.hs"
source-dirs = ["test", "src"]
dependencies = [
  "hspec == 2.*",
  "QuickCheck",
  "temporary",
  "mockery >= 0.3",
  "interpolate",
  "aeson-qq",
]
```

**Comment by sol** [comment]
I only want to consider a particular future at the point somebody actually wants to use it.

So unless you want to use this your self, I would close this ticket without any further thought.

**Comment by sol** [comment]
Closing this for now.

**Comment by jtojnar** [comment]
I would love to use this. Or [JSON](https://github.com/sol/hpack/issues/172). Basically anything else than YAML.

**Comment by sol** [comment]
@jtojnar I understand the common criticism on YAML for it's complexity.  But I prefer YAML over reinventing my own.

I chose YAML over JSON for the following reasons:
 - JSON lacks support for comments, which makes it IMHO unsuitable for anything under revision control.  So we would need to go with some non-standard JSON parser that supports comments.
 - JSON requires commas between list items, which is prone to bikeshedding discussions regarding leading/trailing-commas

I chose YAML over TOML because it's more widely used and already used by other tools in the Haskell community (and elsewhere).

That said, YAML is a superset of JSON.  So you can write your package description in JSON if you want to.
