### ISSUE TITLE
Feature request: Hpack version requirement for package.yaml config

### ISSUE THREAD

**Issue by chrissound** [sol/hpack#192]
Could we possibly add a 'hpack version' field perhaps?

So for example in this situtation: https://github.com/sol/hpack/issues/181, the user could receive an error like "This configuration requires a newer version of hpack".

**Comment by sol** [comment]
@chrissound Hi, thanks for taking the time to open this issue and sorry for the late reply.

Yes, it is sensible to version file formats.  No, I'm not going to do that for `hpack` for now.

As I understand it, this would mean that the user specifies a lower version bound for `hpack` (e.g. `hpack-version: 0.17.0` would imply that this package specification requires `hpack >= 0.17.0`).

I'm not excited about specifying version bounds manually in general.  From my experience specifying version bounds manually is laborsome and error prone (that is they are often times too loose or too tight, but rarely correct).

This is why I favor *dependency pinning* (aka *freezing*) over version bounds. From a certain point of view you could consider it less ambitious, but at least it does not require any manual work. 

## How does `hpack` use pinning?

For `hpack` the generated cabal file double functions as a freeze file for the `hpack` version: A comment at the top of the generated cabal file pins the used `hpack` version.

Technically, it's not pinning, as we use the pinned `hpack` version only as a lower-bound rather than as an exact version requirement.

If you try to re-generate the cabal file and

- `hpack` is older than the pinned version, `hpack` will complain with

      foo.cabal was generated with a newer version of hpack, please upgrade and try again.

- `hpack` is newer than the pinned version and there are changes to the generated cabal file: The cabal file is re-generated and the pinned version is updated.

- `hpack` is newer than the pinned version and there are no actual changes: The cabal file is left as is, the pinned version is not updated.


## In general
I strongly recommend that users always use the latest version of `hpack`. In the past we have mostly added new features to `hpack` while maintaining backwards-compatibility. Given this situation, I don't see a good reason for using an outdated version of `hpack`.

**Comment by sol** [comment]
Closing.

**Comment by sol** [comment]
@chrissound this is implemented as of `hpack-0.29.6`.

**Comment by chrissound** [comment]
Awesome. Thank you!
