### ISSUE TITLE
Handle hsc files more robustly

### ISSUE THREAD

**Issue by fisx** [sol/hpack#353]
to reproduce:

- compile an `hsc` file in your project to its `hs` form (in order to make ghci work).
- run `stack --build`.
- hpack will find the `hs` file and add an entry to the module list.

this will lead to two identical entries for the module, one motivated by the `hsc` file, one motivated by the `hs` file.

desired behavior: if there are two files for one module, one `hsc` and one `hs`, only make one entry.

this is arguably not a bug but odd user behavior, but hpack may be in the best position to solve it.  of course i am also very open to ideas how to fix my tooling.  :-)

thanks!

**Comment by sol** [comment]
@fisx sorry for the late reply.  This will be fixed with the next release (thanks @andreasabel).

> of course i am also very open to ideas how to fix my tooling

I think cabal will drop generated source files into `dist/build/` (or some `new-style` equivalent).  So what I would try is not generate anything within your source tree.  Let cabal take care of generating any modules and add something like `:set -idist/build/` to a `.ghci` file.
