### ISSUE TITLE
Why is there a dependency on http-client(-tls)?

### ISSUE THREAD

**Issue by Profpatsch** [sol/hpack#389]
Grepping through the code I can see that there is one place in the code where for some reason (that was not immediately obvious to me), a Github URL is downloaded.

Given that the hpack tool should be a pure conversion of one text format to another, it seems a bit excessive that I would have to compile the entire Haskell cryptographic and the entire Haskell network stack just for that.

Can we add a flag to disable that? Or even re-evaluate whether e.g. shelling out to `curl` might not be enough for this use-case.

**Comment by sol** [comment]
Hey there, thanks for using `hpack`!

> Why is there a dependency on http-client(-tls)?

I would love to discuss this, however, I currently I don't have the capacity, and I'm not sure if/when this will change.  For now, reading the code is your best bet.

For the time being, we are stuck with that dependency.  How I deal with it:
- Use a build system that does dependency caching, so that I'm not affected by it.
- In situations where this is not practical (e.g. CI), I install binaries with `curl ... https://github.com/sol/hpack/blob/master/get-hpack.sh | bash`
