### ISSUE TITLE
Stackage maintainership

### ISSUE THREAD

**Issue by andreasabel** [sol/hpack#554]
@sol  Maybe it is a good idea that you take stackage maintainership for `hpack` to get alerts from the stackage curators.
Currently `hpack` is orphan, listed under "grandfathered dependencies", and is disabled:
https://github.com/commercialhaskell/stackage/blob/80a5ffcd5ee76cb36be1742103f100351bd824f4/build-constraints.yaml#L5244

**Comment by sol** [comment]
Thanks @andreasabel. As for the specific issue, I think this is fixed by the latest release.

Regarding stackage maintainership, i'm OK if somebody wants to put it under my packages. But I am not opening a PR myself. I'm currently away from the computer and I don't care enough to put it on a to do list or something.
